SITES_MAPPING = {
    'pmc.ncbi.nlm.nih.gov': 'pubmed.ncbi.nlm.nih.gov',
    'ncbi.nlm.nih.gov': 'pubmed.ncbi.nlm.nih.gov',
    'thetimes.co.uk': 'thetimes.com',
    'thetimes.co.ua': 'thetimes.com',
    'en.m.wikipedia.org': 'wikipedia.org',
    'observers.france24.com': 'france24.com',
    'de.wikipedia.org': 'wikipedia.org',
    'en.wikipedia.org': 'wikipedia.org',
    'fr.wikipedia.org': 'wikipedia.org',
    'yahoo.com': 'news.yahoo.com',
    'ca.news.yahoo.com': 'news.yahoo.com',
    'finance.yahoo.com': 'news.yahoo.com',
    'hk.news.yahoo.com': 'news.yahoo.com',
    'uk.news.yahoo.com': 'news.yahoo.com',
    'amp.cnn.com': 'cnn.com',
    'edition.cnn.com': 'cnn.com',
    'ap.org': 'apnews.com',
    'api.politifact.com': 'politifact.com',
    'cdn01.checkyourfact.com': 'checkyourfact.com',
    'live.fullfact.org': 'fullfact.org',
    'amp.dw.com': 'dw.com',
    'southfront.press': 'southfront.org',
    'xn--80abgvjd1bi0f.leadstories.com': 'leadstories.com',
    'xn--h1acbxfam.leadstories.com': 'leadstories.com',
    'czech.leadstories.com': 'leadstories.com',
    'jp.reuters.com': 'reuters.com',
    'prod-ss.aap.com.au': 'aap.com.au',
    'mail.snopes.com': 'snopes.com',
    'fox13seattle.com': 'foxnews.com',
    'hosted.ap.org': 'apnews.com',
    'bmjopen.bmj.com': 'bmj.com',
    'css.washingtonpost.com': 'washingtonpost.com',
    'content.time.com': 'time.com',
    'money.usnews.com': 'usnews.com',
    'respiratory-research.biomedcentral.com': 'biomedcentral.com',
    'bmcpulmmed.biomedcentral.com': 'biomedcentral.com',
    'en.wikisource.org': 'wikipedia.org',
    'es.wikipedia.org': 'wikipedia.org',
    'staging.politifact.com': 'politifact.com',
}

EU_LANGUAGES = [
    'austria',
    'belgium',
    'bulgaria',
    'croatia', 
    'cyprus', 
    'czechia',
    'denmark', 
    'estonia',
    'finland',
    'france',
    'germany', 
    'greece',
    'hungary',
    'ireland',
    'italy',
    'latvia',
    'lithuania',
    'luxembourg',
    'malta', 
    'netherlands',
    'poland',
    'portugal',
    'romania', 
    'slovakia',
    'slovenia',
    'spain',
    'sweden',
]

EU_PAGES = [
    f'https://{lang}.representation.ec.europa.eu/' for lang in EU_LANGUAGES
]

EU_PAGES.extend([
    'https://enlargement.ec.europa.eu/',
    'https://home-affairs.ec.europa.eu/',
    'https://joint-research-centre.ec.europa.eu/',
    'https://knowledge4policy.ec.europa.eu/',
    'https://m.economictimes.com/',
    'https://migrant-integration.ec.europa.eu/',
    'https://bankingsupervision.europa.eu/',
    'https://commission.europa.eu/',
    'https://consilium.europa.eu/',
    'https://ecb.europa.eu/'
    'https://eea.europa.eu/',
    'https://eeas.europa.eu/',
    'https://eesc.europa.eu/',
    'https://eni-seis.eionet.europa.eu/',
    'https://eur-lex.europa.eu/',
    'https://europarl.europa.eu/',
    'https://forum.eionet.europa.eu/',
    'https://iss.europa.eu/',
    'https://op.europa.eu/',
    'https://europrospects.eu/',
    'https://newslettereuropean.eu/',
    'https://ec.europa.eu/',
    'https://europol.europa.eu/',

])

LOCAL_GOV_PAGES = [
    'https://www.mzv.sk/',
    'https://data.unicef.org/',
    'https://unicef.org/',
    'https://19january2021snapshot.epa.gov/',
    'https://9-11commission.gov/',
    'http://ag.ny.gov/',
    'https://alabamaag.gov/',
    'https://archive.cdc.gov/',
    'https://betterhealth.vic.gov.au',
    'https://blogs.cdc.gov/',
    'https://health.gov.au/',
    'https://bls.gov/',
    'https://budget.house.gov/',
    'https://cia.gov/',
    'https://climate.gov/',
    'https://climate.nasa.gov/',
    'https://climatechange.chicago.gov/',
    'https://cms.gov/',
    'https://council.nyc.gov/',
    'https://cpd.gov.ua/',
    'https://csce.gov/'
    'https://defense.gov/',
    'https://disasters.nasa.gov/',
    'https://earthobservatory.nasa.gov/',
    'https://espanol.cdc.gov/',
    'https://fbi.gov/',
    'https://federalregister.gov/',
    'https://genome.gov/',
    'https://gov.scot/',
    'https://govinfo.gov/',
    'https://health.gov.au/',
    'https://ibis.utah.gov/',
    'https://ice.gov/',
    'https://judiciary.house.gov/',
    'https://judiciary.senate.gov/',
    'https://legis.la.gov/'
    'https://naca.gov.ng/',
    'https://nass.usda.gov/',
    'https://nca2014.globalchange.gov/',
    'https://ncei.noaa.gov/',
    'https://nepis.epa.gov/',
    'https://newsonair.gov.in/',
    'https://nhc.noaa.gov/',
    'https://niaid.nih.gov/',
    'https://niehs.nih.gov/',
    'https://ntp.niehs.nih.gov',
    'https://nyc.gov/',
    'https://nycourts.gov/',
    'https://oig.hhs.gov/',
    'https://oversight.house.gov/',
    'https://pubs.usgs.gov/',
    'https://radio.gov.pk/',
    'https://science.gov/',
    'https://science.nasa.gov/',
    'https://science2017.globalchange.gov/',
    'https://state.gov/',
    'https://spravdi.gov.ua/',
    'https://stroke.cindrr.research.va.gov/',
    'https://supremecourt.gov/',
    'https://useu.usmission.gov/',
    'https://usgs.gov/',
    'https://usun.usmission.gov/',
    'http://von.gov.ng/',
    'https://weather.gov/',
    'https://weather.metoffice.gov.uk/',
    'https://2021-2025.state.gov/',
    'https://committees.parliament.uk/',
    'https://commonslibrary.parliament.uk/',
    'https://hansard.parliament.uk/',
    'https://lordslibrary.parliament.uk/',
    'https://publications.parliament.uk/',
    'https://cclg.org.uk/',
    'https://msf.org.uk/',
    'https://ref.org.uk/',
    'https://resus.org.uk/',
    'https://vaccination.org.uk/',
    'https://nature.scot/',
    'https://eea.europa.eu/',
    'https://science.org.au/',
    'https://climate.copernicus.eu/',
    'https://wind-watch.org/',
    'https://eurotoday.org/',
    'https://eurointegration.com.ua/',
    'https://polskieradio.pl/',
    'https://scottishrenewables.com/',
    'https://unian.info/',
    'https://gov.pl/',
    'https://aemet.es/',
    'https://dehst.de/',
    'https://icaew.com/',
    'https://canada.ca/',
    'https://wmo.int/',
    'https://dfrlab.org/',
    'https://lamoncloa.gob.es/',
    'https://rki.de/',
    'https://un.org/',
    'https://pace.coe.int/',
    'https://australian.museum/',
    'https://bmel.de/',
    'https://fao.org/',
    'https://minneapolisfed.org/',
    'https://fred.stlouisfed.org/',
    'https://holodomormuseum.org.ua/',
    'https://new.kenyalaw.org/',
    'https://imf.org/',
    'https://ecre.org/',
    'https://admin.ch/',
    'https://defense.gov/',
    'https://usar.army.mil/',
    'https://army.mil/',
    'https://decisions.sst-tss.gc.ca/',
    'https://alberta.ca/',
    'https://portseattle.org/',
    'https://osce.org/',
    'https://docs.un.org/',
    'https://press.un.org/',
    'https://euneighbourseast.eu/',
    'https://en.um.warszawa.pl/',
    'https://swp-berlin.org/',
    'https://banque-france.fr/',
    'https://nato.int/',
    'https://www.icc-cpi.int/',
    'https://www.bka.de/',
    'https://frontex.europa.eu/',
    'https://vaccination-info.europa.eu/',
    'https://climate.ec.europa.eu/',
    'https://fra.europa.eu/',
    'https://economy-finance.ec.europa.eu/',
    'https://europa.eu/',
    'https://efsa.europa.eu/',
    'https://learning-corner.learning.europa.eu/',
    'https://publications.jrc.ec.europa.eu/',
    'https://digital-strategy.ec.europa.eu/',
    'https://european-union.europa.eu/',
    'https://euaa.europa.eu/',
    'https://ec.europa.eu/',
    'https://europol.europa.eu/',
    'https://employment-social-affairs.ec.europa.eu/',
    'https://prd.frontex.europa.eu/',
    'https://ema.europa.eu/',
    'https://multimedia.europarl.europa.eu/',
    'https://data.europa.eu/',
    'https://climate-adapt.eea.europa.eu/',
    'https://food.ec.europa.eu/',
    'https://finance.ec.europa.eu/',
    'https://policie.gov.cz/',
    'https://fema.gov/',
    'https://dcceew.gov.au/',
    'https://it.usembassy.gov/',
    'https://ninds.nih.gov/',
    'https://energycommerce.house.gov/',
    'https://ecowatch.noaa.gov/',
    'https://dcceew.gov.au/',
    'https://it.usembassy.gov/',
    'https://ninds.nih.gov/',
    'https://energycommerce.house.gov/',
    'https://ecowatch.noaa.gov/',
    'https://earth.gsfc.nasa.gov/',
    'https://seslhd.health.nsw.gov.au/',
    'https://icmr.gov.in/',
    'https://atf.gov/',
    'https://pa.usembassy.gov/',
    'https://globalocean.noaa.gov/',
    'https://metoffice.gov.uk/',
    'https://nccih.nih.gov/',
    'https://pa.gov/',
    'https://cga.ct.gov/',
    'https://statistikaamy.csu.gov.cz/',
    'https://docs.house.gov/',
    'https://media.defense.gov/',
    'https://static.pib.gov.in/',
    'https://beta.cdc.gov/',
    'https://dni.gov/',
    'https://ehp.niehs.nih.gov/',
    'https://apps.usgs.gov/',
    'https://dhs.gov/',
    'https://osti.gov/',
    'https://au.usembassy.gov/',
    'https://tga.gov.au/',
    'https://ddnews.gov.in/',
    'https://csu.gov.cz/',
    'https://publichealth.lacounty.gov/',
    'https://energy.gov/',
    'https://periodicos.capes.gov.br/',
    'https://loc.gov/',
    'https://courtsofnz.govt.nz/',
    'https://minre.gov.ua/',
    'https://arctic.noaa.gov/',
    'https://data.bls.gov/',
    'https://seer.cancer.gov/',
    'https://stateoig.gov/',
    'https://archive.legmt.gov/',
    'https://cfs.gov.hk/',
    'https://arpansa.gov.au/',
    'https://ovc.ojp.gov/',
    'https://oversight.gov/',
    'https://ga.water.usgs.gov/',
    'https://mv.gov.cz/',
    'https://osce.usmission.gov/',
    'https://clinicaltrials.gov/',
    'https://ods.od.nih.gov/',
    'https://nlm.nih.gov/',
    'https://ustr.gov/',
    'https://ua.usembassy.gov/',
    'https://apps.fas.usda.gov/',
    'https://secretservice.gov/',
    'https://kriminalita.policie.gov.cz/',
    'https://cincinnati-oh.gov/',
    'https://legistar.council.nyc.gov/',
    'https://ojp.gov/',
    'https://ndr.nascp.gov.ng/',
    'https://abw.gov.pl/',
    'https://va.gov/',
    'https://mass.gov/',
    'https://radionigeria.gov.ng/',
    'https://fs.usda.gov/',
    'https://odni.gov/',
    'https://justice.gov/',
    'https://netl.doe.gov/',
    'https://vlada.gov.cz/',
    'https://mfa.gov.ua/',
    'https://svs.gsfc.nasa.gov/',
    'https://ojjdp.ojp.gov/',
    'https://nca2018.globalchange.gov/',
    'https://msp.gov.cz/',
    'https://by.usembassy.gov/',
    'https://mindev.gov.ua/',
    'https://ciencia.nasa.gov/',
    'https://president.gov.ua/',
    'https://police.govt.nz/',
    'https://cdph.ca.gov/',
    'https://tpcoe.gov.pl/',
    'https://fcc.gov/',
    'https://consilium-europa.libguides.com/',
    'https://ec-europa-eu.libguides.com/',
    'https://auschwitz.info/',
    'https://ukraine.un.org/',
    'https://www.bmi.bund.de/',
    'https://polizei.bayern.de/',
    'https://osce.delegfrance.org/',
    'https://bmi.bund.de/',
    'https://new-york-un.diplo.de/',
    'https://polizei.de/',
    'https://polizei.sachsen-anhalt.de/',
    'https://dserver.bundestag.de/'
    'https://berlin.de/',
    'https://minv.sk/',
    'https://www.mosr.sk/',
    'https://staryweb.raca.sk/',
]

POLITICS_GOV = [
    'https://cramer.senate.gov/',
    'https://cruz.senate.gov/',
    'https://cassidy.senate.gov/',
    'https://delbene.house.gov/',
    'https://energycommerce.house.gov/',
    'https://murray.senate.gov/',
    'https://republicanleader.senate.gov/',
    'https://trumpwhitehouse.archives.gov/',
    'https://warren.senate.gov/',
    'https://waysandmeans.house.gov/',
    'https://quigley.house.gov/',
    'https://daines.senate.gov/',
    'https://banking.senate.gov/',
    'https://newhouse.house.gov/',
    'https://luttrell.house.gov/',
    'https://risch.senate.gov/',
    'https://bidenwhitehouse.archives.gov/',
    'https://democrats-judiciary.house.gov/',
]

CHINESE_GOV_PAGES = [
    'https://be.china-embassy.gov.cn/',
]

RUSSIA_GOV_PAGES = [
    'https://mid.ru/',
    'https://canada.mid.ru/'
]

EDMO = [
    'https://edmo.eu/',
    'https://cedmohub.eu/',
    'https://admohub.eu/',
    'https://becid.eu/',
    'https://benedmo.eu/',
    'https://brodhub.eu/',
    'https://defacto-observatoire.fr/',
    'https://belux.edmo.eu/',
    'https://edmohub.ie/',
    'https://gadmo.eu/',
    'https://www.hdmo.eu/',
    'https://iberifier.eu/',
    'https://www.idmo.it/',
    'https://meddmo.eu/',
    'https://nordishub.eu/',
    'https://factico.org/',
]

SOCIAL_MEDIA = [
    'https://instagram.com/',
    'https://linkedin.com/',
    'https://m.facebook.com/',
    'https://m.youtube.com/',
    'https://reddit.com/',
    'https://tiktok.com/',
    'https://web.facebook.com/',
    'https://x.com/',
    'https://youtube.com/',
    'https://twitter.com',
    'https://bsky.app/',
]

PUBLICATIONS = [
    'https://arxiv.org/',
    'https://web.stanford.edu/',
    'https://stanford.edu/',
    'https://law.stanford.edu/',
    'https://academic.oup.com/',
    'https://journals.plos.org/',
    'https://heart.org/',
    'https://eelp.law.harvard.edu/',
    'https://health.harvard.edu/',
    'https://hsph.harvard.edu/',
    'https://keith.seas.harvard.edu/',
    'https://misinforeview.hks.harvard.edu/',
    'https://uchicagomedicine.org/',
    'https://mcgill.ca/',
    'https://ahajournals.org/',
    'https://ccf.georgetown.edu/',
    'https://ccf.georgetown.edu/',
    'https://econ.iastate.edu/',
    'https://jsri.msu.edu/',
    'https://legal-forum.uchicago.edu/',
    'https://budgetlab.yale.edu/',
    'https://climate.mit.edu/'
    'https://climatecenter.fsu.edu/',
    'https://dlg.usg.edu/',
    'https://lieber.westpoint.edu/',
    'https://mason.gmu.edu/',
    'https://math.ucr.edu/',
    'https://news.cornell.edu/',
    'https://ropercenter.cornell.edu/',
    'https://news.clemson.edu/',
    'https://news.nau.edu/',
    'https://news.ucsc.edu/',
    'https://scholarlycommons.law.case.edu/',
    'https://site.extension.uga.edu/',
    'https://universityofcalifornia.edu/',
    'https://urmc.rochester.edu/',
    'https://utep.edu/',
    'https://uwa.edu.au/',
    'https://online.ucpress.edu/',
    'https://maxwell.syr.edu/',
    'https://kuh.ku.edu.tr/',
    'https://lclark.edu/',
    'https://cidrap.umn.edu/',
    'https://climatecenter.fsu.edu/',
    'https://american.edu/',
    'https://chop.edu/',
    'https://academicworks.cuny.edu/',
    'https://swlaw.edu/',
    'https://start.umd.edu/',
    'https://sas.rochester.edu/',
    'https://ozyegin.edu.tr/',
    'https://mecco.colorado.edu/',
    'https://firstamendment.mtsu.edu/',
    'https://rockefeller.edu/',
    'https://academia.edu/',
    'https://cancerresearchuk.org/',
    'https://cis.org/',
    'https://health.clevelandclinic.org/',
    'https://journals.sagepub.com/',
    'https://wearemitu.com/',
    'https://bmcpublichealth.biomedcentral.com/',
    'https://europepmc.org/',
    'http://elibrary.imf.org/',
    'https://my.clevelandclinic.org/',
    'https://pharmaceutical-journal.com/',
    'https://journals.lww.com/',
    'https://agupubs.onlinelibrary.wiley.com/',
    'https://cdnsciencepub.com/',
    'https://juniperpublishers.com/',
    'https://publications.ersnet.org/',
    'https://longdom.org/',
    'https://nfid.org/',
    'https://healthychildren.org/',
    'https://nsidc.org/',
    'https://wateractionhub.org/',
    'https://paragoninstitute.org/',
    'https://nebraskamed.com/',
    'https://bmcinfectdis.biomedcentral.com/',
    'https://unaids.org/',
    'https://worldwidecancerresearch.org/',
    'https://icbe-emf.org/',
    'https://onlinelibrary.wiley.com/',
    'https://aafp.org/',
    'https://news.cancerresearchuk.org/',
    'https://emro.who.int/',
    'https://clinmedkaz.org/',
    'https://smw.ch/',
    'https://auntminnieeurope.com/',
    'https://pedspandemicnetwork.org/',
    'https://eatrightpro.org/',
    'https://osi-saf.eumetsat.int/',
    'https://marine.copernicus.eu/',
    'https://healthtalk.unchealthcare.org/',
    'https://interesjournals.org/',
    'https://hopkinsdiabetesinfo.org/',
    'https://clinphytoscience.springeropen.com/',
    'https://sciencepublishinggroup.com/',
    'https://hellodoctor.com.ph/',
    'https://resuscitationjournal.com/',
    'https://naca.gov.ng/',
    'https://mjlh.mcgill.ca/',
    'https://medicalguidelines.msf.org/',
    'https://neuropt.org/',
    'https://apic.org/',
    'https://poisonhelp.org/',
    'https://essd.copernicus.org/',
    'https://sej.org/',
    'https://cp.copernicus.org/',
    'https://tc.copernicus.org/',
    'https://bg.copernicus.org/',
    'https://zew.de/',
    'https://iwm.at/',
    'https://onlineethics.org/',
    'https://research.pej.pt/',
    'https://centreantipoisons.be/',
    'https://naturalhealthresearch.org/',
    'https://dmsjournal.biomedcentral.com/',
    'https://acibademhealthpoint.com/',
    'https://breastcancerconsortium.net/',
    'https://prolifehc.com/',
    'https://pad.ihvnigeria.org/',
    'https://wma.net/',
    'https://cancerireland.ie/',
    'https://iarc.who.int/',
    'https://uhhospitals.org/',
    'https://sagewesthealthcare.com/',
    'https://amjmed.com/',
    'https://strokejournal.org/',
    'https://stroke.org/',
    'https://hra.nhs.uk/',
    'https://aan.com/',
    'https://ascp.org/',
    'https://apha.org/',
    'https://ajog.org/',
    'https://plantsjournal.com/',
    'https://rmets.org/',
    'https://nceo.ac.uk/',
    'https://forests4climate.org/',
    'https://wires.onlinelibrary.wiley.com/',
    'https://ccrc8.niacs.org/',
    'https://mpls.ox.ac.uk/',
    'https://royalsociety.org/',
    'https://lse.ac.uk/',
    'https://earthquakes.bgs.ac.uk/',
    'https://ncl.ac.uk/',
    'https://icsusa.org/',
    'https://aerosociety.com/',
    'https://dinastires.org/',
    'https://icj-cij.org/',
    'https://research.ed.ac.uk/',
    'https://dovepress.com/',
    'https://msf.org/',
    'https://www.nfp-drugs.bg/',
    'https://publications.aap.org/',
    'https://aapc.com/',
    'https://www.icnirp.org/',
    'https://besjournals.onlinelibrary.wiley.com/',
    'https://nph.onlinelibrary.wiley.com/',
    'https://obgyn.onlinelibrary.wiley.com/',
    'https://efsa.onlinelibrary.wiley.com/',
    'https://acsjournals.onlinelibrary.wiley.com/',
    'https://dspace.cvut.cz/',
    'https://fsv.cuni.cz/',
    'https://scholarship.law.slu.edu/',
    'https://repository.uclawsf.edu/',
    'https://news.uci.edu/',
    'https://scholarship.law.uc.edu/',
    'https://vcresearch.berkeley.edu/',
    'https://news.virginia.edu/',
    'https://si.edu/',
    'https://isca.indiana.edu/',
    'https://sanford.duke.edu/',
    'https://washington.edu/',
    'https://gmo.uconn.edu/',
    'https://ctc.westpoint.edu/',
    'https://sites.duke.edu/',
    'https://larc.cardozo.yu.edu/',
    'https://law.unimelb.edu.au/',
    'https://extension.msstate.edu/',
    'https://heart.arizona.edu/',
    'https://jpia.princeton.edu/',
    'https://animalbiotech.ucdavis.edu/',
    'https://scholarship.law.nd.edu/',
    'https://trac.syr.edu/',
    'https://hms.harvard.edu/',
    'https://extension.umd.edu/',
    'https://digitalcommons.montclair.edu/',
    'https://iro.uiowa.edu/',
    'https://studentbriefs.law.gwu.edu/',
    'https://bu.edu/',
    'https://libguides.asu.edu/',
    'https://ysph.yale.edu/',
    'https://uvm.edu/',
    'https://ssi.armywarcollege.edu/',
    'https://ecommons.aku.edu/',
    'https://erc.edu/',
    'https://extremism.gwu.edu/',
    'https://lens.monash.edu/',
    'https://digitalcommons.law.uga.edu/',
    'https://mvec.mcri.edu.au/',
    'https://cires.colorado.edu/',
    'https://sais.jhu.edu/',
    'https://vrp.ucla.edu/',
    'https://publichealth.jhu.edu/',
    'https://health.ucdavis.edu/',
    'https://scholarship.law.vanderbilt.edu/',
    'https://ceepr.mit.edu/',
    'https://mvsu.edu/',
    'https://dsps.lib.uiowa.edu/',
    'https://publichealth.gmu.edu/',
    'https://um.edu.mt/',
    'https://ces.ufl.edu/',
    'https://wtamu.edu/',
    'https://animalscience.ucdavis.edu/',
    'https://digitalcommons.law.udc.edu/',
    'https://scholarship.law.wm.edu/',
    'https://0-www-elibrary-imf-org.library.svsu.edu/',
    'https://digitalcommons.law.ggu.edu/',
    'https://https-crth-hpru-nihr-ac-uk-443.webvpn.ynu.edu.cn/',
    'https://cil.nus.edu.sg/',
    'https://poisoncontrol.utah.edu/',
    'https://scholarworks.law.ubalt.edu/',
    'https://unc.edu/',
    'https://repositorio.comillas.edu/',
    'https://news.berkeley.edu/',
    'https://pharmacy.uconn.edu/',
    'https://agbiotech.ces.ncsu.edu/',
]

DISINFORMATION = [
    'https://nasepravda.cz/',
    'https://balkan.news-pravda.com/',
    'https://czechia.news-pravda.com/',
    'https://hungary.news-pravda.com/',
    'https://en.iz.ru/',
    'https://magyarnemzet.hu/',
    'https://vtforeignpolicy.com/',
    'https://en.topcor.ru/',
    'https://lnr-news.ru/',
    'https://fondfbr.ru/',
    'https://en.topwar.ru/',
    'https://principia-scientific.com/',
    'https://standupcanada.solutions/',
    'https://chriswicknews.com/',
    'https://vaccinetruth.org/',
]

FACT_CHECKING = [
    'https://disa.org/',
    'https://disinfo.detector.media/',
    'https://mythdetector.com/',
    'https://seecheck.org/'
    'https://allsides.com/',
    'https://ukrainefactcheck.org/',
    'https://factcheckafrica.net/',
    'https://checkforfacts.com/',
    'https://portalcheck.org/',
    'https://antidisinfo.net/',
    'https://factually.co/',
    'https://factiverse.ghost.io/',
    'https://factspace.org/',
    'https://aapnews.aap.com.au/',
    'https://kompas.com/',
    'https://blackdotresearch.sg/',
    'https://lighthousejournalism.com/',
    'https://mvau.lt/',
    'https://truthmeter.mk/',
    'https://verifica.efe.com/',
    'https://www.disinfo.eu/',
    'https://factcheck.africa/',
    'https://factcheck.thecable.ng/',
    'https://factchecking.ie/',
    'https://en.detector.media/',
]

RELIABLE_NEWS_SITES = [
    'https://coindesk.com/',
    'https://cointelegraph.com/',
    'https://markets.businessinsider.com/',
    'https://war.ukraine.ua/',
    'https://lansinginstitute.org/',
    'https://today.rtl.lu/',
    'https://pfizer.com/',
    'https://sofiaglobe.com/',
    'https://cfpublic.org/',
    'https://cleanenergywire.org/',
    'https://www.allsides.com/',
    'https://www.pap.pl/',
    'https://english.elpais.com/',
    'https://united24media.com/',
    'https://health.medicaldialogues.in/',
    'https://ukraine.ohchr.org',
    'https://reliefweb.int/',
    'https://toolbox.google.com/',
    'https://transparencyreport.google.com/',
    'https://safety.google/',
]

SITES_CATEGORIES = {
    **{site: 'government' for site in EU_PAGES},
    **{site: 'government' for site in LOCAL_GOV_PAGES},
    **{site: 'fact-checking' for site in EDMO},
    **{site: 'fact-checking' for site in FACT_CHECKING},
    **{site: 'social-media' for site in SOCIAL_MEDIA},
    **{site: 'publications' for site in PUBLICATIONS},
    **{site: 'disinformation' for site in DISINFORMATION},
    **{site: 'reliable-news' for site in RELIABLE_NEWS_SITES},
    **{site: 'disinformation' for site in RUSSIA_GOV_PAGES},
}
